### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by Gnabe** [AISIN-TRC/CBM-AUC#1]
Hello,

What does the memory in the paper refer to?
Is there a comma missing?

Greetings

**Comment by AISIN-TRC** [comment]
Do you mean Table 2 in our paper? This is the mean memory during training measured by nvidia-smi.

**Comment by Gnabe** [comment]
Ah, I see you fixed it. On my version, it  said 2450/2608 GB.
Your current numbers seem a lot more feasible.
Thanks
